Repository entando-ngpl/entando-engine-86d3e302, pull requests merged in 2021-07, with the labels that each got.

#1 ENG-999 GitHub actions pipeline exp2
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/finalization-workflow.yml
  .github/workflows/release_internal_nexus.yml
  .github/workflows/release_maven_central.yml
  owasp-project-suppressions.xml
  pom.xml
  src/test/java/com/agiletec/aps/system/services/group/TestGroupManager.java
  src/test/java/com/agiletec/aps/system/services/keygenerator/KeyGeneratorManagerIntegrationTest.java
  src/test/java/com/agiletec/aps/system/services/lang/LangManagerIntegrationTest.java
  src/test/java/com/agiletec/aps/system/services/lang/LangManagerTest.java
  src/test/java/org/entando/entando/aps/system/init/util/TestQueryExtractor.java
  src/test/java/org/entando/entando/aps/system/services/api/cache/ApiServiceCacheWrapperTest.java
  src/test/java/org/entando/entando/aps/system/services/cache/CacheInfoManagerIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/dataobject/TestDataObjectManager.java
  src/test/java/org/entando/entando/aps/system/services/dataobject/entity/TestDataObjectEntityManager.java
  src/test/java/org/entando/entando/aps/system/services/dataobjectdispender/TestDataObjectDispenser.java
  src/test/java/org/entando/entando/aps/system/services/dataobjectmodel/DataObjectModelDAOIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/dataobjectmodel/DataObjectModelManagerIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/dataobjectmodel/DataObjectModelManagerTest.java
  src/test/java/org/entando/entando/aps/system/services/dataobjectmodel/DataObjectModelServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/dataobjectsearchengine/TestSearchEngineManager.java
  src/test/java/org/entando/entando/aps/system/services/group/GroupServiceTest.java
  src/test/java/org/entando/entando/ent/EmptyTest.java
  src/test/java/org/entando/entando/web/guifragment/validator/GuiFragmentValidatorTest.java
  src/test/java/org/entando/entando/web/pagesettings/PageSettingsControllerTest.java
Labels: prepared

#4 ENG-2471 Checkout via pipelines scripts
  .github/workflows/build-and-test-workflow.yml
Labels: prepared

#6 ENG-2471 Checkout via pipelines scripts
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/pr.yml
  .github/workflows/tag-release-on-merge.yml
  .github/workflows/tag-release.yml
Labels: preflight-check

#8 ENG-2471 Checkout via pipelines scripts
  .github/workflows/tag-release-on-merge.yml
Labels: preflight-check

#10 ENG-2471 Checkout via pipelines scripts
  .github/workflows/pr.yml
  .github/workflows/tag-release-on-merge.yml
Labels: preflight-check

#11 ENG-2471 Checkout via pipelines scripts
  .github/workflows/generate-tag-release.yml
Labels: preflight-check

#12 ENG-2471 Checkout via pipelines scripts
  .github/workflows/generate-tag-release.yml
  .github/workflows/pr.yml
Labels: preflight-check

#3 ENG-2471 preview version tag
  .github/workflows/after-merge-tag-creator.yml
  .github/workflows/build-and-test-workflow.yml
  .github/workflows/nexus-publisher.yml
  pom.xml
Labels: prepared

#18 ENG-0003 test
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  src/main/java/com/agiletec/aps/util/AbstractConfigLoader.java
Labels: prepared, skip-owasp, skip-sonar

#20 ENG-0003 test
  .github/workflows/post-merge.yml
Labels: skip-owasp, skip-sonar

#22 ENG-0005 final test
  .github/workflows/pr.yml
  src/main/java/com/agiletec/aps/util/AbstractConfigLoader.java
Labels: prepared

#21 ENG-0003 test
  .github/workflows/pr.yml
Labels: prepared

#23 ENG-009 Update pr.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  pom.xml
Labels: prepared

#25 ENG-2471 Minor Workflow refinements
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared

#27 ENG-2471 Support docker publication and snyk monitor
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared

#29 ENG-0007 test mvn deploy artifact with javadoc sources and tests
  .github/workflows/publication.yml
Labels: prepared
